### ISSUE TITLE
问下大佬项目中的.g dart文件用什么生成的 AS 插件还是命令

### ISSUE THREAD

**Issue by Reus-Wang168** [RuffianZhong/FlutterApp#3]

**Comment by RuffianZhong** [comment]
@cocach 

FlutterJsonBeanFactory ： json 转 实体类(androidStudio插件)

**Comment by Reus-Wang168** [comment]
这个json conver _content 也是这个插件生成的么，里面东西要自己写吧

**Comment by Reus-Wang168** [comment]
比如bannerentity 类里面的 属性 都改了 具体怎么根据 自己写的banner 类对应json生成 .g 文件的

**Comment by RuffianZhong** [comment]
@cocach 
都是自动生成的，你先查查 FlutterJsonBeanFactory 这个插件的怎么用
